#!/bin/bash
curl -s https://raw.githubusercontent.com/syuneara/neara_apps/main/Dockerfile -o ~/app/config/Dockerfile
curl -s https://raw.githubusercontent.com/syuneara/neara_apps/main/docker-compose.yml -o ~/app/config/docker-compose.yml
